gpus: '0'
workers: 4
print_freq: 100
name: 

dataset:
  name: 'coco'
  root: 'd:/datasets/coco/'
  train_set: 'train2017'
  test_set: 'val2017'
  flip: true
  rot_factor: 40
  scale_factor: 0.3
  unbiased_encoding: false
model:
  name: 'mobilenet_v3_small'
  input_w: 192
  input_h: 256
  output_w: 48
  output_h: 64
  num_joints: 17
  sigma: 2
  final_conv_kernel: 1
  deconv_with_bias: false
  num_deconv_layers: 3
  num_deconv_filters:
  - 256
  - 256
  - 256
  num_deconv_kernels:
  - 4
  - 4
  - 4
loss:
  use_target_weight: true
train:
  batch_size: 32
  epochs: 140
  optimizer: 'adam'
  lr: 0.001
  lr_factor: 0.1
  lr_step:
  - 90
  - 120
test:
  batch_size: 32
  bbox_thr: 1.0
  image_thr: 0.0
  in_vis_thr: 0.2
  nms_thr: 1.0
  oks_thr: 0.9
  use_gt_bbox: true
  distribution_aware: false
